#!/usr/bin/env python3
"""Build a vibe-trading backtest run directory for the entry checklist.

    python3 bt_prepare.py NVDA --strategy ema --run-root ~/.vibe-trading/runs
    python3 bt_prepare.py NVDA --strategy breakout --max-hold-days 126
    python3 bt_prepare.py XAU/USD --strategy squeeze --source yfinance --code GC=F
    python3 bt_prepare.py BTC-USDT --strategy ema --interval 1H --years 2      # intraday, windows stay in days

Writes <run_root>/<TICKER>-<strategy>/config.json and code/signal_engine.py, then
prints the run directory. Feed that path to the `backtest` MCP tool and the
resulting directory to bt_report.py. Stdlib only.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date, timedelta
from pathlib import Path

STRATEGIES = {
    "ema": "vault rule 3 (since 2026-08-24): EMA12 > EMA21 entry, cross-down exit",
    "ma200": "pre-2026-08-24 rule 3: above MA200 within 20%, at MA10/MA50 pullback; exit below MA200",
    "breakout": "Donchian: close above prior 55-day high; exit below prior 20-day low",
    "squeeze": "Bollinger(20,2) width at 120-day low within last 5 bars, then close above upper band; exit below EMA21",
    "macd": "MACD(12,26,9) crosses above signal with close > EMA50; exit on cross down",
    "value": "Volume/Market Profile: 2 closes above the 120d value-area high, POC rising, 5d delta > 0; exit close < POC",
    "pocbounce": "Volume Profile: EMA12 > EMA21, close within band of 120d POC and above it, 5d delta > 0; exit close < VAL",
    "emaflow": "ema entry plus order-flow filters: 5d delta > 0 and close above the 120d POC; exit EMA12 < EMA21",
    "hvnbreak": "guide p.28: close breaks above a high-volume node it sat in, 5d delta > 0; exit close < POC",
    "lvnreject": "guide p.25: low prints inside a low-volume node and close recovers above it; exit close < LVN floor",
    "pocshift": "guide p.23: POC rising over 5d and 10d, close inside value above POC, 5d delta > 0; exit close < VAL or POC stalls 10d",
    "hlhvn": "guide p.29: confirmed higher swing low inside a high-volume node with close > EMA21; exit close < that swing low",
}

ENGINE = '''import numpy as np
import pandas as pd
from typing import Dict

# Generated by trade-check/scripts/bt_prepare.py — vault Investment Entry Checklist.
# Rules 1 (business) and 2 (Fwd vs TTM P/E) have no daily history -> assumed pass.
STRATEGY = {strategy!r}           # see STRATEGIES in bt_prepare.py
PULLBACK_BAND = {pullback_band}   # "at" MA10/MA50 = within this fraction (ma200 mode)
MA200_SAFE_ZONE = {ma200_safe}    # 0-20% above MA200 = safe to enter (ma200 mode)
VOL_RATIO_INST = {vol_ratio}      # rule 5: institutional volume
LONG_LOWER_WICK = {wick}          # rule 5: buyers defending
D = {bars_per_day}                # bars per trading day: 1 = daily, 24 = 1H crypto; windows below are in days
VWAP_WINDOW = {vwap_window}       # daily: 20-session proxy; intraday: true rolling 1-day session VWAP
MAX_HOLD_BARS = {max_hold_bars}   # swing horizon cap; 0 = no cap
PROFILE_WINDOW = {profile_window}
PROFILE_BINS = 50
VALUE_AREA = 0.70


HVN_RATIO, LVN_RATIO = 1.5, 0.5   # bin volume vs mean bin volume


def volume_profile(h, l, c, v, nodes=False):
    """Rolling volume profile on daily bars: each bar's volume sits at its typical price.
    Returns (POC, value-area high, value-area low) for the window ending at each bar.
    With nodes=True also returns, evaluated on the PREVIOUS bar's profile (no look-ahead):
    ratio_at_close, bin_hi_at_close, ratio_at_low, bin_lo_at_low, bin_hi_at_low."""
    tp = ((h + l + c) / 3).to_numpy()
    hi, lo, vol = h.to_numpy(), l.to_numpy(), v.to_numpy()
    n = len(tp)
    poc, vah, val = np.full(n, np.nan), np.full(n, np.nan), np.full(n, np.nan)
    rc, hc, rl, ll, hl = (np.full(n, np.nan) for _ in range(5))
    prev = None
    cl = c.to_numpy()
    for i in range(PROFILE_WINDOW - 1, n):
        if nodes and prev is not None:
            p_hist, p_edges = prev
            mean_bin = p_hist.mean()
            for price, r_out, lo_out, hi_out in ((cl[i], rc, None, hc), (lo[i], rl, ll, hl)):
                k = int(np.clip(np.searchsorted(p_edges, price, side="right") - 1, 0, PROFILE_BINS - 1))
                r_out[i] = p_hist[k] / mean_bin if mean_bin > 0 else np.nan
                hi_out[i] = p_edges[k + 1]
                if lo_out is not None:
                    lo_out[i] = p_edges[k]
        s = slice(i - PROFILE_WINDOW + 1, i + 1)
        edges = np.linspace(lo[s].min(), hi[s].max(), PROFILE_BINS + 1)
        hist, _ = np.histogram(tp[s], bins=edges, weights=vol[s])
        if hist.sum() <= 0:
            continue
        mids = (edges[:-1] + edges[1:]) / 2
        k = int(hist.argmax())
        a = b = k
        acc, target = hist[k], hist.sum() * VALUE_AREA
        while acc < target and (a > 0 or b < PROFILE_BINS - 1):   # expand toward the heavier side
            up = hist[b + 1] if b < PROFILE_BINS - 1 else -1
            dn = hist[a - 1] if a > 0 else -1
            if up >= dn:
                b += 1; acc += up
            else:
                a -= 1; acc += dn
        poc[i], vah[i], val[i] = mids[k], edges[b + 1], edges[a]
        prev = (hist, edges)
    idx = h.index
    out = (pd.Series(poc, idx), pd.Series(vah, idx), pd.Series(val, idx))
    if nodes:
        out += (pd.Series(rc, idx), pd.Series(hc, idx), pd.Series(rl, idx), pd.Series(ll, idx), pd.Series(hl, idx))
    return out


class SignalEngine:
    def generate(self, data_map: Dict[str, pd.DataFrame]) -> Dict[str, pd.Series]:
        out = {{}}
        for code, df in data_map.items():
            c, o, h, l, v = df["close"], df["open"], df["high"], df["low"], df["volume"]
            tp = (h + l + c) / 3
            vwap = (tp * v).rolling(VWAP_WINDOW).sum() / v.rolling(VWAP_WINDOW).sum()
            vol_ratio = v / v.rolling(20 * D).mean()
            rng = (h - l).replace(0, np.nan)
            lower_wick = (np.minimum(o, c) - l) / rng

            e12, e21 = c.ewm(span=12 * D, adjust=False).mean(), c.ewm(span=21 * D, adjust=False).mean()
            if STRATEGY == "ema":            # swing trend: EMA12 over EMA21
                rule3, trend_exit = e12 > e21, e12 < e21
            elif STRATEGY == "ma200":        # legacy rule 3 (pre-2026-08-24)
                ma10, ma50, ma200 = c.rolling(10 * D).mean(), c.rolling(50 * D).mean(), c.rolling(200 * D).mean()
                above = (c > ma200) & (c / ma200 - 1 <= MA200_SAFE_ZONE)
                at_ma = ((c / ma10 - 1).abs() <= PULLBACK_BAND) | ((c / ma50 - 1).abs() <= PULLBACK_BAND)
                rule3, trend_exit = above & at_ma, c < ma200
            elif STRATEGY == "breakout":     # Donchian 55-high entry / 20-low exit
                rule3 = c > h.rolling(55 * D).max().shift(1)
                trend_exit = c < l.rolling(20 * D).min().shift(1)
            elif STRATEGY == "squeeze":      # Bollinger squeeze (tightest in 120d) then upper-band break
                mid, sd = c.rolling(20 * D).mean(), c.rolling(20 * D).std()
                width = (4 * sd) / mid
                tight = (width.rolling(120 * D).min() == width).rolling(5 * D).max().fillna(0).astype(bool)
                rule3, trend_exit = tight & (c > mid + 2 * sd), c < e21
            elif STRATEGY == "macd":         # MACD cross up above EMA50 / cross down
                macd = e12 - c.ewm(span=26 * D, adjust=False).mean()
                sigl = macd.ewm(span=9 * D, adjust=False).mean()
                rule3 = (macd > sigl) & (macd.shift(1) <= sigl.shift(1)) & (c > c.ewm(span=50 * D, adjust=False).mean())
                trend_exit = macd < sigl
            elif STRATEGY in ("hvnbreak", "lvnreject", "pocshift", "hlhvn"):
                poc, vah, val, r_close, hi_close, r_low, lo_low, hi_low = volume_profile(h, l, c, v, nodes=True)
                poc1, vah1, val1 = poc.shift(1), vah.shift(1), val.shift(1)
                delta5 = (v * (2 * (c - l) / rng - 1)).rolling(5 * D).sum()
                if STRATEGY == "hvnbreak":     # yesterday's close sat in an HVN; today closes above that node
                    rule3 = (r_close.shift(1) >= HVN_RATIO) & (c > hi_close.shift(1)) & (delta5 > 0)
                    trend_exit = c < poc1
                elif STRATEGY == "lvnreject":  # today's low printed in an LVN; close recovered above the node
                    rule3 = (r_low <= LVN_RATIO) & (c > hi_low)
                    floor = lo_low.where(rule3).ffill()
                    trend_exit = c < floor
                elif STRATEGY == "pocshift":   # value migrating up; buy inside value above POC
                    rising = (poc1 > poc1.shift(5 * D)) & (poc1.shift(5 * D) > poc1.shift(10 * D))
                    rule3 = rising & (c > poc1) & (c <= vah1) & (delta5 > 0)
                    trend_exit = (c < val1) | (poc1 <= poc1.shift(10 * D))
                else:                          # hlhvn: confirmed higher swing low inside an HVN
                    W = 10 * D
                    swing = (l.shift(W) == l.rolling(2 * W + 1).min())            # low W bars ago is the min of +-W
                    swing_low = l.shift(W).where(swing)
                    prev_swing = swing_low.ffill().shift(1).where(swing)
                    higher = (swing_low > prev_swing) & (r_low.shift(W) >= HVN_RATIO)
                    state = higher.where(swing).ffill().infer_objects(copy=False).fillna(False).astype(bool)   # persists until the next swing
                    stop = swing_low.where(swing).ffill()
                    rule3 = state & (c > e21) & (c > stop) & (delta5 > 0)
                    trend_exit = c < stop
            elif STRATEGY in ("value", "pocbounce", "emaflow"):
                poc, vah, val = volume_profile(h, l, c, v)
                poc1, vah1, val1 = poc.shift(1), vah.shift(1), val.shift(1)
                delta5 = (v * (2 * (c - l) / rng - 1)).rolling(5 * D).sum()   # order-flow proxy: buyers in control
                if STRATEGY == "value":      # acceptance above value, POC migrating up
                    accepted = (c > vah1) & (c.shift(1) > vah1.shift(1))
                    rule3 = accepted & (poc1 > poc1.shift(20 * D)) & (delta5 > 0)
                    trend_exit = c < poc1
                elif STRATEGY == "pocbounce":  # pullback to POC inside an EMA uptrend
                    at_poc = (c >= poc1) & (c / poc1 - 1 <= PULLBACK_BAND)
                    rule3 = (e12 > e21) & at_poc & (delta5 > 0)
                    trend_exit = c < val1
                else:                        # ema trend with order-flow confirmation
                    rule3 = (e12 > e21) & (delta5 > 0) & (c > poc1)
                    trend_exit = e12 < e21
            else:
                raise ValueError(STRATEGY)
            rule4 = c > vwap
            rule5 = (c > o) & ((vol_ratio >= VOL_RATIO_INST) | (lower_wick >= LONG_LOWER_WICK))

            entry = (rule3 & rule4 & rule5).fillna(False).to_numpy()
            exit_ = trend_exit.fillna(False).to_numpy()

            sig = np.zeros(len(df))
            holding, held = False, 0
            for i in range(len(df)):
                if holding:
                    held += 1
                    if exit_[i] or (MAX_HOLD_BARS and held >= MAX_HOLD_BARS):
                        holding = False
                elif entry[i]:
                    holding, held = True, 0
                sig[i] = 1.0 if holding else 0.0
            out[code] = pd.Series(sig, index=df.index)
        return out
'''


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("ticker", help="US ticker, e.g. NVDA; or a vibe-trading code (700.HK, BTC-USDT, XAU/USD)")
    ap.add_argument("--strategy", choices=sorted(STRATEGIES), default="ema",
                    help="; ".join(f"{k}: {v}" for k, v in STRATEGIES.items()))
    ap.add_argument("--source", default="auto", help="vibe-trading data source (auto, yfinance, okx, ...)")
    ap.add_argument("--code", help="override the instrument code sent to the data source (e.g. GC=F for gold on yfinance)")
    ap.add_argument("--max-hold-days", type=int, default=0, help="time exit in sessions (126 ≈ 6 months); 0 = none")
    ap.add_argument("--interval", default="1D", help="bar size: 1D (default) or an intraday size like 1H")
    ap.add_argument("--bars-per-day", type=int, help="scale for intraday windows (default: 24 for crypto 1H, 7 for equities 1H, 1 for 1D)")
    ap.add_argument("--years", type=float, default=None, help="history length (default 10 for 1D, 1 for intraday)")
    ap.add_argument("--end", default=date.today().isoformat())
    ap.add_argument("--run-root", default=str(Path.home() / ".vibe-trading" / "runs"),
                    help="must be one of vibe-trading's allowed run roots")
    ap.add_argument("--thresholds", help="thresholds.json (defaults to the bundled one)")
    ap.add_argument("--name", help="run dir name (default <TICKER>-<strategy>[-h<maxhold>])")
    a = ap.parse_args(argv)

    T = json.loads((Path(a.thresholds) if a.thresholds
                    else Path(__file__).resolve().parent.parent / "references" / "thresholds.json").read_text())
    code = a.code or (a.ticker.upper() if any(ch in a.ticker for ch in "./-=") else f"{a.ticker.upper()}.US")
    intraday = a.interval.upper() != "1D"
    bpd = a.bars_per_day or (1 if not intraday else (24 if code.endswith("-USDT") else 7))
    years = a.years if a.years is not None else (1 if intraday else 10)
    end = date.fromisoformat(a.end)
    start = end - timedelta(days=int(365 * years))
    slug = "".join(ch if ch.isalnum() else "" for ch in a.ticker.upper())
    name = a.name or f"{slug}-{a.strategy}" + (f"-h{a.max_hold_days}" if a.max_hold_days else "") + (f"-{a.interval.lower()}" if intraday else "")
    run_dir = Path(a.run_root).expanduser() / name
    (run_dir / "code").mkdir(parents=True, exist_ok=True)

    config = {
        "source": a.source, "codes": [code],
        "start_date": start.isoformat(), "end_date": end.isoformat(), "interval": a.interval,
        "initial_cash": 1_000_000, "commission": 0.001,
        "extra_fields": None, "fundamental_fields": None, "optimizer": None, "optimizer_params": {},
        "engine": "daily", "position_adjustment": "hold", "rebalance_tolerance": 0.05,
        "validation": {"bootstrap": {"n_bootstrap": 1000, "confidence": 0.95}, "walk_forward": {"n_windows": 5}},
    }
    (run_dir / "config.json").write_text(json.dumps(config, indent=2) + "\n")
    (run_dir / "code" / "signal_engine.py").write_text(ENGINE.format(
        strategy=a.strategy, pullback_band=T["pullback_band_pct"] / 100, ma200_safe=T["ma200_safe_zone_pct"] / 100,
        vol_ratio=T["volume_ratio_institutional"], wick=T["long_lower_wick_pct"] / 100,
        bars_per_day=bpd, vwap_window=20 if bpd == 1 else bpd, max_hold_bars=a.max_hold_days * bpd,
        profile_window=120 * bpd))
    print(run_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
